### ISSUE TITLE
Please add a list of required packages

### ISSUE THREAD

**Issue by kelgazza** [noise-lab/iot-inspector-client#4]
please consider putting all required packages in a requirements.txt file.
```$pip install -r requirements.txt```

**Comment by crazyideas21** [comment]
Thanks! Working on the linux/mac build instructions. Will keep y'all posted.

**Comment by crazyideas21** [comment]
The linux build instructions are available. See https://iot-inspector.princeton.edu/blog/post/getting-started/#i-class-fab-fa-linux-i-linux

**Comment by AnthonyMastrean** [comment]
So, a [requirements file](https://pip.pypa.io/en/stable/reference/pip_install/?highlight=requirements#requirements-file-format) is still a better and more standardized solution than the [ad hoc install dependencies script](https://github.com/noise-lab/iot-inspector-client/blob/master/v2-src/linux-install-dependencies.sh).

Even more, if I'm trying to run this script in a Docker container, I have no `sudo`.

```
root@651602b2125d:/usr/local/src/iot-inspector-client-master/v2-src# ./linux-install-dependencies.sh
./linux-install-dependencies.sh: line 4: sudo: command not found
./linux-install-dependencies.sh: line 5: sudo: command not found
./linux-install-dependencies.sh: line 6: sudo: command not found
./linux-install-dependencies.sh: line 7: sudo: command not found
./linux-install-dependencies.sh: line 8: sudo: command not found
./linux-install-dependencies.sh: line 9: sudo: command not found
./linux-install-dependencies.sh: line 10: sudo: command not found
```

Is there a problem using requirements.txt because you're installing packages from both pip2 and pip3?

**Comment by nealmcb** [comment]
And what's up with pip2 and pip3? How does it work to mix Python 2 and Python 3?
Especially for those of us trying to install this in a virtual environment (see #25), so it doesn't pollute our main package libraries?
